### ISSUE TITLE
Sync crashes due to: pika.exceptions.ConnectionClosed: (-1, "ConnectionResetError(104, 'Connection reset by peer')")

### ISSUE THREAD

**Issue by Achse** [Achse/coinrat#49]
```
ERROR:pika.adapters.base_connection:Socket Error: 104
ERROR:pika.adapters.blocking_connection:Connection close detected; result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, reason_code=-1, reason_text="ConnectionResetError(104, 'Connection reset by peer')")
Traceback (most recent call last):
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/bin/coinrat", line 11, in <module>
    load_entry_point('coinrat', 'console_scripts', 'coinrat')()
  File "/home/achse/workspace/achse/coinrat/coinrat/coinrat.py", line 345, in main
    cli(obj={})
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/achse/workspace/achse/coinrat/coinrat/coinrat.py", line 205, in synchronize
    synchronizer.synchronize(pair_obj)
  File "/home/achse/workspace/achse/coinrat/coinrat_bittrex/synchronizer.py", line 45, in synchronize
    self._event_emitter.emit_new_candles(self._storage.name, candles)
  File "/home/achse/workspace/achse/coinrat/coinrat/event/event_emitter.py", line 28, in emit_new_candles
    'storage': candle_storage,
  File "/home/achse/workspace/achse/coinrat/coinrat/event/event_emitter.py", line 40, in emit_event
    self.channel.basic_publish(exchange='', routing_key='events', body=json.dumps(event))
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish
    mandatory, immediate)
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2164, in publish
    self._flush_output()
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1250, in _flush_output
    *waiters)
  File "/home/achse/.local/share/virtualenvs/coinrat-LJBZUXvf/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 474, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
``

**Comment by nitinlko** [comment]
Hi,
I am new to python and rabbitmq. i am also facing same error. my consumer runs and processes messages for 7-8 hours then i get this error. Can you please elaborate, how to resolve this.
i see you mentioned about synchronizers. Can you please elaborate.

**Comment by Achse** [comment]
I have found this interesting comment: https://github.com/pika/pika/issues/732#issuecomment-209535461

**Comment by Achse** [comment]
Btw @nitinlko do you use also UI app? If not, you do not need those rabbitMQ events (they are used only for visualizing the incoming candle in UI in real-time). You can disable using RabbitMQ at all by setting 
```bash
EVENT_EMITTER=null
```
In `.env` file.

**Comment by Achse** [comment]
Also this could help: https://github.com/pika/pika/issues/779#issuecomment-368152949 (some advice how to configure rabbitMQ in production)
